name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    - name: Deploy to Production
      run: |
       git init
git init
git add .
git commit -m "first commit"
git remote add origin https://github.com/mararie12/world.git
git branch -M master
git push -u origin master

